<!--
/**
 * Magenizr ResetUiBookmarks
 *
 * @category    Magenizr
 * @package     Magenizr_ResetUiBookmarks
 * @copyright   Copyright (c) 2018 Magenizr (http://www.magenizr.com)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
-->

<div class="magenizr-resetuibookmarks">
    <div class="divider"></div>
    <fieldset class="fieldset admin__fieldset " id="magenizr_resetuibookmarks">
        <legend class="admin__legend">
            <span><?php echo __('Reset UI Bookmarks') ?></span>
        </legend><br>

        <div class="admin__field">
            <label class="label admin__field-label"></label>
            <div class="admin__field-control control">
                <a href="<?php echo $block->getUrl('resetuibookmarks/reset/index', ['_current' => true, '_use_rewrite' => true]); ?>" class="action-default scalable button-danger">
                    <span><?php echo __('Reset UI Bookmarks') ?></span>
                </a>
                <span class="hint">
                    <?php echo __('This will reset your UI bookmarks such as state of filters, column positions, grid sorting, pagination and so on.') ?>
                </span>
            </div>
        </div>
    </fieldset>
</div>